/*


*/
SELECT ID_LOG, TEXT_LOG, EXEC_DATETIME, NAME_STATUS, NAME_CLASSNAME, NAME_WORKSTATION, NAME_USER 
FROM TB_LOG, TB_USER, TB_WORKSTATION, TB_CLASSNAME, TB_STATUS
WHERE TB_LOG.ID_USER = TB_USER.ID_USER 
AND TB_LOG.ID_WORKSTATION = TB_WORKSTATION.ID_WORKSTATION 
AND TB_LOG.ID_CLASSNAME = TB_CLASSNAME.ID_CLASSNAME 
AND TB_LOG.ID_STATUS = TB_STATUS.ID_STATUS
AND NAME_STATUS IN ('FAILED','PASSED','TITLE') 
AND EXEC_DATETIME BETWEEN '2021-01-21 20:27:00' AND '2021-01-21 20:27:59' 
ORDER BY EXEC_DATETIME;


CREATE TABLE TB_USER(
	ID_USER INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	NAME_USER VARCHAR(512) UNIQUE
);
CREATE TABLE TB_WORKSTATION(
	ID_WORKSTATION INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME_WORKSTATION VARCHAR(512) UNIQUE
);
CREATE TABLE TB_CLASSNAME(
	ID_CLASSNAME INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME_CLASSNAME VARCHAR(512) UNIQUE
);
CREATE TABLE TB_STATUS(
	ID_STATUS INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME_STATUS VARCHAR(512) UNIQUE
);
CREATE TABLE TB_LOG(
	ID_LOG INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	TEXT_LOG VARCHAR(512),
	EXEC_DATETIME TIMESTAMP,
	ID_USER INT NOT NULL,
	ID_WORKSTATION INT NOT NULL,
	ID_CLASSNAME INT NOT NULL,
	ID_STATUS INT NOT NULL,
	CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID_USER),
	CONSTRAINT FK_WORKSTATION FOREIGN KEY (ID_WORKSTATION) REFERENCES TB_WORKSTATION(ID_WORKSTATION),
	CONSTRAINT FK_CLASSNAME FOREIGN KEY (ID_CLASSNAME) REFERENCES TB_CLASSNAME(ID_CLASSNAME),
	CONSTRAINT FK_STATUS FOREIGN KEY (ID_STATUS) REFERENCES TB_STATUS(ID_STATUS)
);

INSERT INTO TB_STATUS(NAME_STATUS) VALUES('FAILED');
INSERT INTO TB_STATUS(NAME_STATUS) VALUES('PASSED');
INSERT INTO TB_STATUS(NAME_STATUS) VALUES('INFORMATION');
INSERT INTO TB_STATUS(NAME_STATUS) VALUES('TITLE');

INSERT INTO TB_USER(NAME_USER) VALUES('username');
INSERT INTO TB_WORKSTATION(NAME_WORKSTATION) VALUES('deskname');
INSERT INTO TB_CLASSNAME(NAME_CLASSNAME) VALUES('classname');



DROP CONSTRAINT FK_USER;
DROP CONSTRAINT FK_WORKSTATION;
DROP CONSTRAINT FK_CLASSNAME;
DROP CONSTRAINT FK_STATUS;
DROP CONSTRAINT FK_LOG;
DROP TABLE TB_USER;
DROP TABLE TB_WORKSTATION;
DROP TABLE TB_CLASSNAME;
DROP TABLE TB_STATUS;
DROP TABLE TB_LOG;